### ISSUE TITLE
local files

### ISSUE THREAD

**Issue by abearab** [anhtr/HPAanalyze#13]
Is it possible to download datasets only once and use your package with those local files?

**Comment by anhtr** [comment]
Hi. You can always save your R objects as .rds or .rdata files and load them back later. You can also use the historical built-in data files from here https://github.com/HPAanalyze/HPAassets. Please see http://www.sthda.com/english/wiki/saving-data-into-r-data-format-rds-and-rdata for how to work with these files.

Sideloading data is on my bucket list, but it is not high priority as long as the HPA portal is still up and running.
